name: Build and Deploy Blazor WebAssembly to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch full history
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
          
      - name: Restore dependencies
        run: dotnet restore
        
      - name: Publish Blazor WebAssembly
        run: dotnet publish -c Release -o release --nologo
        
      - name: Add .nojekyll file
        run: touch release/wwwroot/.nojekyll
        
      - name: Fix base href for GitHub Pages
        run: |
          REPO_NAME="${{ github.event.repository.name }}"
          sed -i 's|<base href="/" />|<base href="/'"$REPO_NAME"'/" />|g' release/wwwroot/index.html
          
      - name: Copy index.html to 404.html
        run: cp release/wwwroot/index.html release/wwwroot/404.html
        
      - name: Create gh-pages branch if it doesn't exist
        run: |
          if ! git show-ref --verify --quiet refs/remotes/origin/gh-pages; then
            echo "Creating gh-pages branch..."
            git checkout --orphan gh-pages
            git rm -rf .
            git clean -fxd
          else
            echo "gh-pages branch already exists"
            git checkout gh-pages
          fi
          
      - name: Deploy files to gh-pages
        run: |
          # Copy built files to current directory
          cp -r release/wwwroot/* .
          
          # Configure git
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          # Add and commit files
          git add .
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Deploy Blazor WebAssembly to GitHub Pages"
            git push origin gh-pages
          fi
