name: Build and Deploy Blazor WebAssembly to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
          
      - name: Restore dependencies
        run: dotnet restore
        
      - name: Publish Blazor WebAssembly
        run: dotnet publish -c Release -o release --nologo
        
      - name: Add .nojekyll file
        run: touch release/wwwroot/.nojekyll
        
      - name: Copy index.html to 404.html (for GitHub Pages SPA support)
        run: cp release/wwwroot/index.html release/wwwroot/404.html
        
      - name: Fix base href for GitHub Pages
        run: |
          sed -i 's/<base href="\/" \/>/<base href="\/'"$GITHUB_REPOSITORY"'\/" \/>/g' release/wwwroot/index.html
          sed -i 's/<base href="\/" \/>/<base href="\/'"$GITHUB_REPOSITORY"'\/" \/>/g' release/wwwroot/404.html
        env:
          GITHUB_REPOSITORY: ${{ github.event.repository.name }}
          
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: release/wwwroot

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4